# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure(2) do |config|
  config.vm.box      = "opscode/centos-6.5"
  config.vm.box_url  = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"

  config.vm.hostname = "centos-vagrant"
  config.vm.network "private_network", ip: "192.168.33.102"

  config.vm.provision :itamae do |conf|
    conf.sudo    = true
    conf.shell   = "/bin/bash"
  end
end
