---
- name: Install build essentials
  package:
      state: latest
      name: "{{ item }}"
  loop:
    - dh-autoreconf
    - pkg-config
- name: Clone ctags repository
  git:
    dest: /tmp/ctags
    depth: 1
    repo: https://github.com/universal-ctags/ctags
- name: 'Install universal-ctags'
  shell: |
    ./autogen.sh
    ./configure
    make
    make install
  args:
    creates: /usr/local/bin/ctags
    chdir: /tmp/ctags