---
- name: install "{{ item }}"
  apt:
    name:
      - ack-grep
      - apache2-utils
      - dstat
      - git
      - git-core
      - jq
      - screen
      - sqlite3
      - tmux
      - tree
      - zip
      - zsh
    state: latest
- import_tasks: ctags.yml
- import_tasks: vim.yml
