---
- name: Install essential packages.
  package:
    state: latest
    name: "{{ item }}"
  loop:
    - build-essential
    - curl
    - default-libmysqlclient-dev
    - libcairo2-dev
    - libgif-dev
    - libjpeg-dev
    - libpango1.0-dev
    - librsvg2-dev
    - ntp
    - tmpreaper
    - traceroute
    - tzdata
    - unzip
    - wget
    - whois