---
- name: Install locale
  package:
    state: latest
    name: locales

- name: Intall language files
  locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - "en_US"
    - "en_US.UTF-8"
    - "ja_JP.UTF-8"
