---
- name: Install python3
  apt:
    name:
      - python3
      - python3-pip
- name: Downgrade pip 9.0.3
  # https://github.com/ansible/ansible-container/issues/919#issuecomment-394018163
  pip:
    name: pip
    version: 9.0.3
