# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure(2) do |config|
  config.vm.box      = "opscode/ubuntu-14.04-i386"
  config.vm.box_url  = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04-i386_chef-provisionerless.box"

  config.vm.hostname = "ubuntu32"
  config.vm.network "private_network", ip: "192.168.33.102"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", inline: <<-CMD
    sudo apt-get update -y \\
    && sudo apt-get install -y ruby2.0 git \\
    && sudo gem2.0 i itamae --no-rdoc --no-ri
  CMD
end
